baseURL = "http://arthurmasson.xyz"
title = "AM"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 15
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
DefaultContentLanguage = "en"

[params.info]
description = "Arthur Masson works"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["assets/css/custom.css"]
customJS = ["assets/js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Arthur Masson"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = "ArthurMasson"
email = "arthur.yves.robin@gmail.com"
facebook = "ArthurMasson"
github = "arthursw"
instagram = "ArthurMasson"
linkedin = "arthurmasson"
twitter = "ArthurMasson"
telegram = "ArthurMasson"

[params.social.config]
platforms = ["github","email"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "AM"
weight = -220
identifier = "arthurmasson"
url = "/"

[[menu.main]]
name = "Applications"
identifier = "applications"
url = "/tags/application"

[[menu.main]]
name = "Reflections"
identifier = "reflections"
url = "/tags/reflection"

[[menu.main]]
name = "Experiments"
identifier = "experiments"
url = "/tags/experiment"

[[menu.main]]
name = "Websites"
identifier = "websites"
url = "/tags/website"

[[menu.main]]
name = "Art"
identifier = "art"
url = "/tags/artwork"

[[menu.main]]
name = "La Sophiste"
identifier = "la-sophiste"
url = "/tags/la-sophiste"

[[menu.main]]
name = "IDLV"
identifier = "idlv"
url = "/tags/idlv"

[blackfriday]
hrefTargetBlank = true

[Languages]
[Languages.en]
title = "AM"
weight = 1

[Languages.fr]
title = "AM"
weight = 2
[languages.fr.blackfriday]
angledQuotes = true