baseURL = "http://arthurmasson.xyz"
title = "AM"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 15
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
DefaultContentLanguage = "en"

[params.info]
description = "Arthur Masson works"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["assets/css/custom.css"]
customJS = ["assets/js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Arthur Masson"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = "ArthurMasson"
email = "arthur.yves.robin@gmail.com"
facebook = "ArthurMasson"
github = "arthursw"
instagram = "ArthurMasson"
linkedin = "arthurmasson"
twitter = "ArthurMasson"
telegram = "ArthurMasson"

[params.social.config]
platforms = ["github","email"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[Languages]
[Languages.en]
title = "AM"
languageName = "English"
weight = 1
[[Languages.en.menu.main]]
name = "AM"
weight = -220
identifier = "arthurmasson"
url = "/"
[[Languages.en.menu.tags]]
name = "Applications"
identifier = "application"
url = "/tags/application/"
[[Languages.en.menu.tags]]
name = "Reflections"
identifier = "reflection"
url = "/tags/reflection/"
[[Languages.en.menu.tags]]
name = "Experiments"
identifier = "experiment"
url = "/tags/experiment/"
[[Languages.en.menu.tags]]
name = "Websites"
identifier = "websites"
url = "/tags/website/"
[[Languages.en.menu.tags]]
name = "Art"
identifier = "art"
url = "/tags/artwork/"
[[Languages.en.menu.co]]
name = "La Sophiste"
identifier = "la-sophiste"
url = "/tags/la-sophiste/"
[[Languages.en.menu.co]]
name = "IDLV"
identifier = "idlv"
url = "/tags/idlv/"
[[Languages.en.menu.workamount]]
name = "1 to 18 hours"
identifier = "from1to18hours"
url = "/tags/from1to18hours/"
[[Languages.en.menu.workamount]]
name = "1 to 18 days"
identifier = "from1to18days"
url = "/tags/from1to18days/"
[[Languages.en.menu.workamount]]
name = "1 to 18 months"
identifier = "from1to18months"
url = "/tags/from1to18months/"

[Languages.fr]
title = "AM"
languageName = "Français"
weight = 2
[languages.fr.blackfriday]
angledQuotes = true
# [languages.fr.settings]
# date & time format: https://golang.org/pkg/time/
# dateFormat = "02 January 2006"
# listDateFormat = "02 January 2006"
[[Languages.fr.menu.main]]
name = "AM"
weight = -220
identifier = "arthurmasson"
url = "/fr/"
[[Languages.fr.menu.tags]]
name = "Applications"
identifier = "application"
url = "/fr/tags/application/"
[[Languages.fr.menu.tags]]
name = "Réflexions"
identifier = "reflection"
url = "/fr/tags/reflection/"
[[Languages.fr.menu.tags]]
name = "Expériences"
identifier = "experiment"
url = "/fr/tags/experiment/"
[[Languages.fr.menu.tags]]
name = "Sites web"
identifier = "website"
url = "/fr/tags/website/"
[[Languages.fr.menu.tags]]
name = "Art"
identifier = "artwork"
url = "/fr/tags/artwork/"
[[Languages.fr.menu.co]]
name = "La Sophiste"
identifier = "la-sophiste"
url = "/fr/tags/la-sophiste/"
[[Languages.fr.menu.co]]
name = "IDLV"
identifier = "idlv"
url = "/fr/tags/idlv/"
[[Languages.fr.menu.workamount]]
name = "1 à 18 heures"
identifier = "from1to18hours"
url = "/fr/tags/from1to18hours/"
[[Languages.fr.menu.workamount]]
name = "1 à 18 jours"
identifier = "from1to18days"
url = "/fr/tags/from1to18days/"
[[Languages.fr.menu.workamount]]
name = "1 à 18 mois"
identifier = "from1to18months"
url = "/fr/tags/from1to18months/"